name: tests

on: [ push, pull_request ]


jobs:
  unit_test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Install dependancies
        run: |
          sudo apt-get update -y
          sudo apt-get install libcmocka-dev cmake -y

      - name: Test
        run: |
          cmake -Btests/build -Htests/ && make -C tests/build/ && make -C tests/build test